---
title: "Turtle_Project"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(here)
library(RColorBrewer)
library(naniar)
library(ggthemes)
options(scipen=999)
``` 

```{r}
turtles <- readr::read_csv(here("Final Project", "Data", "pop_survey_tagging_data.csv")) %>% clean_names()
```
```{r}
glimpse(turtles)
```
```{r}
turtles

```
Some of the numerical data uses 0 as NAs, and actual NAs. 

```{r}
summary(turtles)
```
```{r}
naniar::miss_var_summary(turtles)
```
```{r}
turtles %>% 
  select(sex_testosterone_level_2)
```
```{r}
turtles %>% 
  group_by(gear) %>%
  ggplot(aes(x = gear, fill = species))+
  geom_bar()+
  coord_flip()+
  scale_y_log10()+
    scale_fill_brewer(palette = "BrBG")+
  labs(title = "Methods of Turtle Capture/sighting",
       x = "n",
       y= "Method")+
    theme_linedraw()+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), plot.title = element_text(size = rel(1.5), hjust = 0.5))
             
  
```
```{r}
turtles %>% 
  group_by(year) %>% 
  ggplot(aes(x = year, fill = cap_region))+
  geom_bar()+
  labs(title = "Turtle Capture by Location",
       x = "Year",
       y= "n")+
    theme_linedraw()+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), plot.title = element_text(size = rel(1.5), hjust = 0.5))
             
  
```
```{r}
turtles %>% 
    na_if("0") %>%
  summary(weight)
```
```{r}
turtles %>% 
    mutate(mass_category = case_when(weight <= 30 ~ "small", weight >= 30 ~ "large")) %>% 
  group_by(year) %>% 
  ggplot(aes(x = year, fill = mass_category))+
  geom_bar()+
  labs(title = "Turtle Capture by Weight Class",
       x = "Year",
       y= "n")+
    theme_linedraw()+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), plot.title = element_text(size = rel(1.5), hjust = 0.5))
```

